version: '2'

services:
  mysql:
    build:
      context: mariadb/
    container_name: vuetify_admin_mysql
    volumes:
      - mysqldata:/var/lib/mysql
      - mysqllog:/var/log/mysql
      - ./mariadb/conf.d:/etc/mysql/conf.d:ro
      - ./mariadb/my.cnf:/etc/mysql/my.cnf:ro
      -  /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    networks:
      - net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_vuefity_admin
    restart: always

  vuetify-admin:
    build:
      context:  vuetify-admin/
    container_name: vuetify-admin
    ports:
      - "8001:80"
    volumes:
      - ./vuetify-admin/dist:/usr/share/nginx/html
      - ./vuetify-admin/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - net
    restart: always
    
  
  vuetify-admin-api:
    build:
      context: vuetify-admin-api/src/vuetify-admin-api/
    container_name: vuetify-admin-api
    volumes:
      - ./vuetify-admin-api/src/vuetify-admin-api/vuetify-admin-api:/app/vuetify-admin-api
      - ./vuetify-admin-api/src/vuetify-admin-api/app/config/config.yml.prod:/app/app/config/config.yml:ro
      - /usr/local/go/lib/time/zoneinfo.zip:/usr/local/go/lib/time/zoneinfo.zip:ro
    ports:
      - "8002:8000"
    networks:
      - net
    restart: always
    depends_on:
      - mysql


volumes:
  mysqldata:
    driver: local
  mysqllog:
    driver: local
  

networks:
  net:
    driver: bridge
